// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	. "github.com/Tualua/gozfsapi/internal/models"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /readyz)
	GetReadyz(ctx echo.Context) error
	// Clone a ZFS dataset
	// (POST /zfs/clone)
	CloneZfsDataset(ctx echo.Context) error
	// List ZFS datasets
	// (GET /zfs/list)
	ListZfsDatasets(ctx echo.Context, params ListZfsDatasetsParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetReadyz converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadyz(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadyz(ctx)
	return err
}

// CloneZfsDataset converts echo context to params.
func (w *ServerInterfaceWrapper) CloneZfsDataset(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CloneZfsDataset(ctx)
	return err
}

// ListZfsDatasets converts echo context to params.
func (w *ServerInterfaceWrapper) ListZfsDatasets(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListZfsDatasetsParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListZfsDatasets(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/readyz", wrapper.GetReadyz)
	router.POST(baseURL+"/zfs/clone", wrapper.CloneZfsDataset)
	router.GET(baseURL+"/zfs/list", wrapper.ListZfsDatasets)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUTU/cMBD9K9a0x2izlJ5yg7ZUlXpiOYH2YJIJa/AXnslKYZX/XtnOLixJS5G4RR77",
	"zZv35mUHtTPeWbRMUO2A6g0amT5/hODCJZJ3ljAe+OA8BlaYyhjL8aNBqoPyrJyFKr8SBonkHUIB3HuE",
	"CoiDsncwDAUEfOxUwAaqmxFkfbjmbu+xZhgKuL5YfdPO4iU+TnuT60KN0+ardC4ayZKQBTtRRwzRBmem",
	"XApgGe6QpzhX6fyAY6VB0bogeIMZ8c3BRoaHFn8Z8XvuMJ1QbqXS8lanISe8jesse6csz5Yj39lCR5Hd",
	"7g3u6fm/CV+lUpStlZ1mqEBqDQWg7UyEaJVG6okxyk5Weto4hgK2TncGj89unXswMjxAkUDWU2mHApRt",
	"XWKuOGoCP51YKeM1iuuLlTjzKoJjoOzfyWIZ+TqPVnoFFZwulotTKMBL3iR9y4Cy6Z/i57gBUX0Z/f/V",
	"RHzky3wjapMzkB5+WS5n9g7DVtUoFImEGzkPBZRPLZV5X6LBjmYapSW/bmm/CdkKJD53TR+v184yZqOl",
	"91rV6W15T7HzPrDx63PAFir4VD4nuhzjXL5M03DsN4cOh8mQJx/Zej9b6nys3FjKqWoEdXWNRG2ndR8d",
	"/JrV/hAix/+zGS7nshGj+IVQdiu1aoSXQRpkDJRyQp0xMvR744RM+9ccBhxN1yp7PbtbvxXxs+OU1vLQ",
	"pLrZgYpsHjsMPezDnDNRvFvzFNRhWM9v8X/rqhgNvcfpQ4hlCLKfU/tMRJGEa18q+FrkKNXreryAYbsX",
	"qwsaKtgwe6rKUnq1yNUFI3G5PYFhPfwJAAD//+IRblnmBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
