// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error *string `json:"error,omitempty"`
}

// ZFSDatasetGetReq defines model for ZFSDatasetGetReq.
type ZFSDatasetGetReq struct {
	// Name Name of dataset to retrieve
	Name string `json:"name"`

	// Properties List of properties to retrieve for the dataset
	Properties []string `json:"properties"`
}

// ZFSDatasetGetResp defines model for ZFSDatasetGetResp.
type ZFSDatasetGetResp struct {
	Properties []ZFSDatasetProp `json:"properties"`
}

// ZFSDatasetProp defines model for ZFSDatasetProp.
type ZFSDatasetProp struct {
	// Name Name of the dataset property
	Name string `json:"name"`

	// Value Value of the dataset property
	Value string `json:"value"`
}

// GetZfsGetJSONRequestBody defines body for GetZfsGet for application/json ContentType.
type GetZfsGetJSONRequestBody = ZFSDatasetGetReq
